# Generated by Django 5.1 on 2024-08-23 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_description', models.TextField(max_length=500)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('product_stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos/products/')),
                ('is_available', models.BooleanField(default=True)),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
